---
- name: copy tmux configuration file
  copy:
    src: ./files/tmux.conf
    dest: "/home/{{ user }}/.tmux.conf"
    owner: "{{ user }}"
    group: "{{ user }}" 
    mode: 0644

- name: copy vimrc
  copy:
    src: ./files/vimrc
    dest: "/home/{{ user }}/.vimrc"
    owner: "{{ user }}"
    group: "{{ user }}" 
    mode: 0644
